namespace Application.Comments
{
    public class CommentDto
    {
        //the first three are easily(auto) generated by Automapper
        public int Id { get; set; }
        public DateTime CreatedAt { get; set; }
        public string Body { get; set; }
        //these below needs mapping
        public string Username { get; set; }
        public string DisplayName { get; set; }
        public string Image { get; set; }
    }
}